"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Data = any;
const fmt = (value: unknown, digits = 2) => value == null || value === "" ? "—" : typeof value === "number" ? value.toFixed(digits) : String(value);
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const pct = (value: number | null) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;

function Badge({ children, tone = "muted" }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Card({ title, value, detail, tone = "blue" }: { title: string; value: string; detail?: string; tone?: string }) { return <article className="kpi"><div className="kpi-top"><span>{title}</span><i className={`dot ${tone}`} /></div><strong>{value}</strong>{detail && <small>{detail}</small>}</article>; }
function LineChart({ points, threshold }: { points: Array<{ date: string; ratio: number | null }>; threshold: number }) {
  const values = points.map((p) => p.ratio).filter((v): v is number => v != null); const max = Math.max(threshold, ...values, 1.4); const min = 0;
  const path = values.length > 1 ? values.map((v, i) => `${i ? "L" : "M"}${(i / (values.length - 1)) * 100},${96 - ((v - min) / (max - min)) * 78}`).join(" ") : "";
  return <div className="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" x2="100" y1={96 - (threshold / max) * 78} y2={96 - (threshold / max) * 78} className="threshold" /><path d={path} className="line" /></svg><div className="chart-labels"><span>Histórico de ratio WAPE</span><span>Umbral {threshold.toFixed(2)}</span></div></div>;
}

export default function Dashboard() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [lastRefresh, setLastRefresh] = useState<Date | null>(null); const [filter, setFilter] = useState("all");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/dashboard", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); setError(""); setLastRefresh(new Date()); } catch (e) { setError(e instanceof Error ? e.message : "Error consultando datos"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); const timer = setInterval(load, 300000); return () => clearInterval(timer); }, [load]);
  const rows = useMemo(() => data?.executions?.history?.filter((row: any) => filter === "all" || (filter === "alert" ? row.alert : row.status === filter)) ?? [], [data, filter]);
  if (loading && !data) return <main className="shell"><div className="loading">Cargando observabilidad del modelo…</div></main>;
  if (error && !data) return <main className="shell"><div className="error">{error}<button onClick={load}>Reintentar</button></div></main>;
  const d = data.drift; const decision = d.retrain ? ["REENTRENAMIENTO RECOMENDADO", "red"] : d.alert ? ["DRIFT DETECTADO", "amber"] : "OK"; const decisionTone = Array.isArray(decision) ? decision[1] : "green";
  const featureNames = ["demand", "event_intensity", "rain_forecast", "rain_mm", "temperature_c", "temperature_forecast"];
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark">P</span><div><b>PULSO / MLOps</b><span>Control room de demanda TransMi</span></div></div><div className="top-actions"><span className="live"><i /> LIVE · lectura</span><span className="updated">Actualizado {lastRefresh ? lastRefresh.toLocaleTimeString("es-CO") : "—"}</span><button className="refresh" onClick={load} disabled={loading}>↻ {loading ? "Actualizando" : "Actualizar"}</button></div></header>
    <section className="hero"><div><p className="eyebrow">MONITOREO DEL MODELO</p><h1>Salud operativa <em>en una mirada.</em></h1><p className="subtitle">Estado del modelo, rendimiento y drift basado en las últimas evaluaciones registradas.</p></div><div className="hero-status"><span>ESTADO ACTUAL</span><Badge tone={decisionTone}>{Array.isArray(decision) ? decision[0] : decision}</Badge><small>{date(d.checkedAt)}</small></div></section>
    {error && <div className="inline-error">{error}</div>}{data.sourceErrors?.length > 0 && <div className="inline-error">Supabase no está respondiendo para: {data.sourceErrors.map((item: any) => item.table).join(", ")}. Los datos faltantes no se estiman; revisa la disponibilidad del proyecto en Supabase.</div>}
    <section className="kpis"><Card title="Modelo activo" value={data.model?.version ?? "Sin modelo"} detail={`${data.model?.algorithm ?? "—"} · entrenado ${date(data.model?.trainedAt)}`} /><Card title="WAPE actual" value={pct(data.performance.current)} detail={`Baseline ${pct(data.performance.baseline)}`} tone="violet" /><Card title="Ratio de rendimiento" value={fmt(data.performance.ratio)} detail={`Límite ${d.thresholds.ratio.toFixed(2)}`} tone={data.performance.ratio >= d.thresholds.ratio ? "red" : "green"} /><Card title="PSI máximo" value={fmt(d.maxPsi)} detail={`${d.drifted.length} de ${featureNames.length} variables con drift`} tone={d.maxPsi >= d.thresholds.psi ? "amber" : "green"} /><Card title="Reentrenamiento" value={d.retrain ? "SÍ" : "NO"} detail={d.retrain ? "Recomendación activa" : "No recomendado"} tone={d.retrain ? "red" : "green"} /><Card title="Salud del pipeline" value={data.pipeline.sync?.status ?? data.pipeline.latest?.status ?? "—"} detail={`${data.executions.failedCount} ejecuciones fallidas`} tone={data.executions.failedCount ? "red" : "green"} /></section>
    <section className="grid-main"><article className="panel decision-panel"><div className="panel-head"><div><p className="eyebrow">DECISIÓN EXPLICADA</p><h2>Estado del modelo / Recomendación</h2></div><Badge tone={decisionTone}>{Array.isArray(decision) ? decision[0] : decision}</Badge></div><div className={`decision ${decisionTone}`}><div className="decision-icon">{decisionTone === "green" ? "✓" : "!"}</div><div><strong>{Array.isArray(decision) ? decision[0] : "El modelo está dentro de los parámetros"}</strong><p>{d.reason}</p></div></div><div className="rule-list"><div><span>Variables con PSI ≥ {d.thresholds.psi.toFixed(2)}</span><b>{d.drifted.length} / {d.thresholds.required} requeridas</b></div><div><span>Ratio WAPE actual / baseline</span><b>{fmt(data.performance.ratio)} / {d.thresholds.ratio.toFixed(2)}</b></div><div><span>Última ejecución</span><b>{date(data.executions.latest?.date)}</b></div></div></article><article className="panel performance"><div className="panel-head"><div><p className="eyebrow">RENDIMIENTO</p><h2>Tendencia de WAPE</h2></div><Badge tone="muted">Últimas evaluaciones</Badge></div><LineChart points={data.performance.history} threshold={d.thresholds.ratio} /><div className="legend"><span><i className="legend-line" /> Ratio WAPE</span><span><i className="legend-dash" /> Umbral</span></div></article></section>
    <section className="grid-main"><article className="panel"><div className="panel-head"><div><p className="eyebrow">DATA DRIFT</p><h2>Señales por variable</h2></div><span className="panel-note">Umbral PSI {d.thresholds.psi.toFixed(2)}</span></div><div className="feature-list">{featureNames.map((name) => { const value = Number(d.psi[name] ?? 0); const hit = value >= d.thresholds.psi; return <div className="feature" key={name}><div className="feature-name"><span>{name}</span><Badge tone={hit ? "amber" : "green"}>{hit ? "DRIFT" : "OK"}</Badge></div><div className="bar-wrap"><div className={`bar ${hit ? "hit" : ""}`} style={{ width: `${Math.min(100, (value / Math.max(d.thresholds.psi * 2, 1)) * 100)}%` }} /><div className="bar-threshold" style={{ left: `${Math.min(100, (d.thresholds.psi / Math.max(d.thresholds.psi * 2, 1)) * 100)}%` }} /></div><b>{fmt(value, 3)}</b></div>})}</div></article><article className="panel alerts"><div className="panel-head"><div><p className="eyebrow">SISTEMA</p><h2>Alertas activas</h2></div><span className="alert-count">{(d.alert ? 1 : 0) + (data.executions.failedCount ? 1 : 0)}</span></div><div className="alert-items">{d.maxPsi >= d.thresholds.psi && <div className="alert-item amber"><span>△</span><div><b>PSI sobre umbral</b><small>Máximo {fmt(d.maxPsi, 3)} · umbral {d.thresholds.psi.toFixed(2)}</small></div></div>}{data.performance.ratio >= d.thresholds.ratio && <div className="alert-item red"><span>↗</span><div><b>Rendimiento degradado</b><small>Ratio {fmt(data.performance.ratio)} supera {d.thresholds.ratio.toFixed(2)}</small></div></div>}{data.executions.failedCount > 0 && <div className="alert-item red"><span>×</span><div><b>Ejecución de drift fallida</b><small>{data.executions.failedCount} ejecución(es) con error</small></div></div>}{!d.alert && !data.executions.failedCount && <div className="empty">✓ No hay alertas activas en este momento.</div>}</div><div className="system-foot"><span>Último éxito</span><b>{date(data.executions.lastSuccess)}</b></div></article></section>
    <section className="panel history"><div className="panel-head"><div><p className="eyebrow">AUDITORÍA</p><h2>Historial de drift</h2></div><div className="filters"><button className={filter === "all" ? "selected" : ""} onClick={() => setFilter("all")}>Todas</button><button className={filter === "success" ? "selected" : ""} onClick={() => setFilter("success")}>Exitosas</button><button className={filter === "error" ? "selected" : ""} onClick={() => setFilter("error")}>Fallidas</button><button className={filter === "alert" ? "selected" : ""} onClick={() => setFilter("alert")}>Con alerta</button></div></div><div className="table-scroll"><table><thead><tr><th>Fecha / hora</th><th>Versión</th><th>PSI máx.</th><th>Variables</th><th>WAPE / base</th><th>Ratio</th><th>Resultado</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td>{date(row.date)}</td><td><code>{row.version}</code></td><td>{fmt(row.psi, 3)}</td><td>{row.drifted} / {featureNames.length}</td><td>{pct(row.wape)} <span className="muted">/ {pct(row.baseline)}</span></td><td>{fmt(row.ratio)}</td><td><Badge tone={row.status === "error" ? "red" : row.alert ? "amber" : "green"}>{row.status === "error" ? "ERROR" : row.alert ? "ALERTA" : "OK"}</Badge></td></tr>)}</tbody></table></div></section>
    <section className="panel model-history"><div className="panel-head"><div><p className="eyebrow">REGISTRO DE MODELOS</p><h2>Versiones disponibles</h2></div><span className="panel-note">{data.models.length} versiones registradas</span></div><div className="model-cards">{data.models.map((model: any) => <div className={`model-card ${model.id === data.model?.id ? "active" : ""}`} key={model.id}><div><code>{model.version}</code>{model.id === data.model?.id && <Badge tone="blue">ACTIVO</Badge>}</div><strong>{model.algorithm ?? "Modelo"}</strong><small>{date(model.trainedAt)}</small><span>{model.mlflowModelVersion ? `MLflow v${model.mlflowModelVersion}` : model.mlflowRunId ? `Run ${model.mlflowRunId.slice(0, 10)}…` : "Sin referencia MLflow"}</span></div>)}</div></section>
    <footer>Solo lectura · Las consultas al dashboard no ejecutan drift ni modifican datos de Supabase.</footer>
  </main>;
}
