"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Histogram, RetrainRug, TimeChart } from "./charts";

type Data = any;
const fmt = (value: unknown, digits = 2) => value == null || value === "" ? "—" : typeof value === "number" ? value.toFixed(digits) : String(value);
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const ago = (value: string | null | undefined) => { if (!value) return "—"; const minutes = Math.max(0, Math.round((Date.now() - Date.parse(value)) / 60000)); return minutes < 60 ? `hace ${minutes} min` : `hace ${(minutes / 60).toFixed(1)} h`; };
const pct = (value: number | null) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;

function Badge({ children, tone = "muted" }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Card({ title, value, detail, tone = "blue" }: { title: string; value: string; detail?: string; tone?: string }) { return <article className="kpi"><div className="kpi-top"><span>{title}</span><i className={`dot ${tone}`} /></div><strong>{value}</strong>{detail && <small>{detail}</small>}</article>; }
const SERIES_TRAIN = "#3987e5";
const SERIES_PROD = "#d95926";
const RANGES = [["24h", 24], ["72h", 72], ["7 días", 168]] as const;
const METRICS: Array<{ key: string; label: string; format: (v: number) => string; better: "lower" | "higher"; hint: string }> = [
  { key: "wape", label: "WAPE", format: (v) => `${(v * 100).toFixed(2)}%`, better: "lower", hint: "Error absoluto / demanda total" },
  { key: "mae", label: "MAE", format: (v) => v.toFixed(2), better: "lower", hint: "Error absoluto medio (pasajeros)" },
  { key: "rmse", label: "RMSE", format: (v) => v.toFixed(2), better: "lower", hint: "Penaliza errores grandes" },
  { key: "r2", label: "R²", format: (v) => v.toFixed(4), better: "higher", hint: "Varianza explicada" },
  { key: "accuracy", label: "Accuracy", format: (v) => `${v.toFixed(2)}%`, better: "higher", hint: "100 × (1 − WAPE)" },
  { key: "cv_mae_mean", label: "MAE validación cruzada", format: (v) => v.toFixed(2), better: "lower", hint: "Media de los folds temporales" },
];
const testMetrics = (training: any) => training?.metrics?.test ?? training?.metrics ?? {};
const prodAccuracy = (wape: number | null | undefined) => wape == null ? null : 100 * Math.max(0, 1 - wape);
const DISTRIBUTIONS: Array<{ key: string; title: string; source: "retrains" | "checks"; value: (row: any) => number | null; format: (v: number) => string }> = [
  { key: "wape", title: "WAPE prueba", source: "retrains", value: (r) => r.wape, format: (v) => `${(v * 100).toFixed(2)}%` },
  { key: "mae", title: "MAE", source: "retrains", value: (r) => r.mae, format: (v) => v.toFixed(2) },
  { key: "rmse", title: "RMSE", source: "retrains", value: (r) => r.rmse, format: (v) => v.toFixed(2) },
  { key: "r2", title: "R²", source: "retrains", value: (r) => r.r2, format: (v) => v.toFixed(4) },
  { key: "accuracy", title: "Accuracy prueba", source: "retrains", value: (r) => r.accuracy, format: (v) => `${v.toFixed(2)}%` },
  { key: "accuracy_prod", title: "Accuracy reciente", source: "checks", value: (c) => c.accuracy ?? prodAccuracy(c.recentWape), format: (v) => `${v.toFixed(2)}%` },
];

function MetricTile({ label, value, previous, format, better, hint }: { label: string; value: number | null; previous: number | null; format: (v: number) => string; better: "lower" | "higher"; hint: string }) {
  const delta = value != null && previous != null ? value - previous : null;
  const same = delta == null || Math.abs(delta) < 1e-9;
  const improved = !same && (better === "lower" ? (delta as number) < 0 : (delta as number) > 0);
  return <div className="metric"><span>{label}</span><strong>{value == null ? "—" : format(value)}</strong><small className={same ? "" : improved ? "up" : "down"}>{delta == null ? "Sin modelo previo" : same ? "= igual que el anterior" : `${improved ? "▲ mejor" : "▼ peor"} · ${delta > 0 ? "+" : "−"}${format(Math.abs(delta))}`}</small><em>{hint}</em></div>;
}

function LineChart({ points, threshold }: { points: Array<{ date: string; ratio: number | null }>; threshold: number }) {
  const values = points.map((p) => p.ratio).filter((v): v is number => v != null); const max = Math.max(threshold, ...values, 1.4); const min = 0;
  const path = values.length > 1 ? values.map((v, i) => `${i ? "L" : "M"}${(i / (values.length - 1)) * 100},${96 - ((v - min) / (max - min)) * 78}`).join(" ") : "";
  return <div className="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" x2="100" y1={96 - (threshold / max) * 78} y2={96 - (threshold / max) * 78} className="threshold" /><path d={path} className="line" /></svg><div className="chart-labels"><span>Histórico de ratio WAPE</span><span>Umbral {threshold.toFixed(2)}</span></div></div>;
}

export default function Dashboard() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [lastRefresh, setLastRefresh] = useState<Date | null>(null); const [filter, setFilter] = useState("all"); const [range, setRange] = useState<number>(24);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/dashboard", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); setError(""); setLastRefresh(new Date()); } catch (e) { setError(e instanceof Error ? e.message : "Error consultando datos"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); const timer = setInterval(load, 300000); return () => clearInterval(timer); }, [load]);
  const rows = useMemo(() => data?.executions?.history?.filter((row: any) => filter === "all" || (filter === "alert" ? row.alert : row.status === filter)) ?? [], [data, filter]);
  const timeline = useMemo(() => {
    const t = data?.timeline ?? { retrains: [], checks: [] };
    const retrains = t.retrains.map((r: any) => ({ ...r, t: Date.parse(r.date) }));
    const checks = t.checks.map((c: any) => ({ ...c, t: Date.parse(c.date) }));
    return { retrains, checks };
  }, [data]);
  const domain = useMemo<[number, number]>(() => { const end = lastRefresh?.getTime() ?? Date.now(); return [end - range * 3600000, end]; }, [range, lastRefresh]);
  if (loading && !data) return <main className="shell"><div className="loading">Cargando observabilidad del modelo…</div></main>;
  if (error && !data) return <main className="shell"><div className="error">{error}<button onClick={load}>Reintentar</button></div></main>;
  const d = data.drift; const liveAccuracy: number | null = data.performance.accuracy ?? prodAccuracy(data.performance.current); const decision = d.retrain ? ["REENTRENAMIENTO RECOMENDADO", "red"] : d.alert ? ["DRIFT DETECTADO", "amber"] : "OK"; const decisionTone = Array.isArray(decision) ? decision[1] : "green";
  const featureNames = ["demand", "event_intensity", "rain_forecast", "rain_mm", "temperature_c", "temperature_forecast"];
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark">P</span><div><b>PULSO / MLOps</b><span>Control room de demanda TransMi</span></div></div><div className="top-actions"><span className="live"><i /> LIVE · lectura</span><span className="updated">Actualizado {lastRefresh ? lastRefresh.toLocaleTimeString("es-CO") : "—"}</span><button className="refresh" onClick={load} disabled={loading}>↻ {loading ? "Actualizando" : "Actualizar"}</button></div></header>
    <section className="hero"><div><p className="eyebrow">MONITOREO DEL MODELO</p><h1>Salud operativa <em>en una mirada.</em></h1><p className="subtitle">Estado del modelo, rendimiento y drift basado en las últimas evaluaciones registradas.</p></div><div className="hero-status"><span>ESTADO ACTUAL</span><Badge tone={decisionTone}>{Array.isArray(decision) ? decision[0] : decision}</Badge><small>{date(d.checkedAt)}</small></div></section>
    {error && <div className="inline-error">{error}</div>}{data.sourceErrors?.length > 0 && <div className="inline-error">Supabase no está respondiendo para: {data.sourceErrors.map((item: any) => item.table).join(", ")}. Los datos faltantes no se estiman; revisa la disponibilidad del proyecto en Supabase.</div>}
    <section className="kpis"><Card title="Modelo activo" value={data.model?.version ?? "Sin modelo"} detail={`${data.model?.algorithm ?? "—"} · entrenado ${date(data.model?.trainedAt)}`} /><Card title="WAPE actual" value={pct(data.performance.current)} detail={`Baseline ${pct(data.performance.baseline)}`} tone="violet" /><Card title="Ratio de rendimiento" value={fmt(data.performance.ratio)} detail={`Límite ${d.thresholds.ratio.toFixed(2)}`} tone={data.performance.ratio >= d.thresholds.ratio ? "red" : "green"} /><Card title="PSI máximo" value={fmt(d.maxPsi)} detail={`${d.drifted.length} de ${featureNames.length} variables con drift`} tone={d.maxPsi >= d.thresholds.psi ? "amber" : "green"} /><Card title="Reentrenamientos 24 h" value={String(data.retraining?.last24h ?? 0)} detail={`Último ${ago(data.retraining?.last)} · cada ${data.retraining?.scheduleHours ?? 1} h · drift ${d.retrain ? "lo recomienda" : "no lo recomienda"}`} tone={d.retrain ? "red" : data.retraining?.last24h ? "green" : "amber"} /><Card title="Salud del pipeline" value={data.pipeline.sync?.status ?? data.pipeline.latest?.status ?? "—"} detail={`${data.executions.failedCount} ejecuciones fallidas`} tone={data.executions.failedCount ? "red" : "green"} /></section>
    <section className="panel current-metrics"><div className="panel-head"><div><p className="eyebrow">MÉTRICAS ACTUALES</p><h2>Modelo activo en evaluación de prueba</h2></div><span className="panel-note">{data.previousTraining ? `Comparado con ${data.previousTraining.version}` : "Sin modelo previo"}</span></div><div className="metric-grid">{METRICS.map((m) => { const cur = testMetrics(data.training)[m.key]; const prev = testMetrics(data.previousTraining)[m.key]; return <MetricTile key={m.key} label={m.label} value={typeof cur === "number" ? cur : null} previous={typeof prev === "number" ? prev : null} format={m.format} better={m.better} hint={m.hint} />; })}<div className="metric prod"><span>WAPE en producción</span><strong>{pct(data.performance.current)}</strong><small className={data.performance.ratio == null ? "" : data.performance.ratio >= d.thresholds.ratio ? "down" : "up"}>{data.performance.ratio == null ? "Sin evaluación de drift" : `Ratio ${fmt(data.performance.ratio)} · límite ${d.thresholds.ratio.toFixed(2)}`}</small><em>Última evaluación de drift · {date(d.checkedAt)}</em></div><div className="metric prod"><span>Accuracy reciente</span><strong>{liveAccuracy == null ? "—" : `${liveAccuracy.toFixed(2)}%`}</strong>{liveAccuracy == null ? <small>Sin evaluación reciente</small> : <small className={liveAccuracy < data.performance.accuracyThreshold ? "down" : "up"}>{liveAccuracy < data.performance.accuracyThreshold ? "▼ bajo el umbral · reentrenar" : "▲ sobre el umbral"} de {data.performance.accuracyThreshold}%</small>}<em>{data.performance.accuracySource === "forecast" ? "Pronósticos vs. demanda observada" : "Evaluación en la ventana reciente"} · reentrena si baja de {data.performance.accuracyThreshold}%</em></div></div><div className="metric-foot"><span>Entrenado {date(data.model?.trainedAt)}</span><span>Tiempo de entrenamiento {fmt(testMetrics(data.training).training_seconds, 1)} s</span><span>Estabilidad CV (σ MAE) {fmt(testMetrics(data.training).cv_mae_std)}</span></div></section>
    <section className="panel timeline"><div className="panel-head"><div><p className="eyebrow">DRIFT Y REENTRENAMIENTOS</p><h2>Cómo cambia el modelo en el tiempo</h2></div><div className="filters">{RANGES.map(([label, hours]) => <button key={hours} className={range === hours ? "selected" : ""} onClick={() => setRange(hours)}>{label}</button>)}</div></div>
      <TimeChart title="WAPE: prueba al reentrenar vs. producción" domain={domain} yMax={Math.max(0.2, ...timeline.retrains.map((r: any) => r.wape ?? 0), ...timeline.checks.map((c: any) => c.recentWape ?? 0)) * 1.15} yFormat={(v) => `${(v * 100).toFixed(0)}%`} series={[{ key: "train", label: "WAPE prueba", color: SERIES_TRAIN, step: true, format: (v) => `${(v * 100).toFixed(2)}%`, points: timeline.retrains.map((r: any) => ({ t: r.t, y: r.wape })) }, { key: "prod", label: "WAPE producción", color: SERIES_PROD, format: (v) => `${(v * 100).toFixed(2)}%`, points: timeline.checks.map((c: any) => ({ t: c.t, y: c.recentWape })) }]} />
      <TimeChart title="Variables con drift (PSI ≥ umbral)" height={170} domain={domain} yMax={featureNames.length} yTicks={featureNames.length / 2} yFormat={(v) => v.toFixed(0)} reference={{ y: d.thresholds.required, label: `Alerta con ${d.thresholds.required}` }} markers={timeline.checks.filter((c: any) => c.alert).map((c: any) => ({ t: c.t, y: c.drifted.length, label: c.retrain ? "Alerta de drift · reentrenamiento recomendado" : "Alerta de drift" }))} series={[{ key: "drifted", label: "Variables con drift", color: SERIES_TRAIN, step: true, format: (v) => `${v.toFixed(0)} de ${featureNames.length}`, points: timeline.checks.map((c: any) => ({ t: c.t, y: c.drifted.length })) }]} />
      <RetrainRug domain={domain} events={[...timeline.retrains.map((r: any) => ({ t: r.t, label: `Modelo #${r.model} · WAPE ${pct(r.wape)}`, tone: "muted" as const })), ...timeline.checks.filter((c: any) => c.retrain).map((c: any) => ({ t: c.t, label: "Drift recomendó reentrenar", tone: "red" as const }))]} />
      <details className="timeline-table"><summary>Ver tabla de reentrenamientos en el rango</summary><div className="table-scroll"><table><thead><tr><th>Fecha / hora</th><th>Modelo</th><th>WAPE prueba</th><th>MAE</th><th>RMSE</th></tr></thead><tbody>{timeline.retrains.filter((r: any) => r.t >= domain[0]).slice().reverse().map((r: any) => <tr key={`${r.model}-${r.t}`}><td>{date(r.date)}</td><td><code>#{r.model}</code></td><td>{pct(r.wape)}</td><td>{fmt(r.mae)}</td><td>{fmt(r.rmse)}</td></tr>)}</tbody></table></div></details>
      <div className="dist-head"><h3>Distribución de las métricas en el rango</h3><span>Prueba: una muestra por reentrenamiento · Producción: una por evaluación de drift · línea punteada = modelo activo</span></div>
      <div className="dist-grid">{DISTRIBUTIONS.map((m) => { const rows = (m.source === "retrains" ? timeline.retrains : timeline.checks).filter((row: any) => row.t >= domain[0] && row.t <= domain[1]); const values = rows.map(m.value).filter((v: number | null): v is number => typeof v === "number"); const current = m.source === "checks" ? liveAccuracy : testMetrics(data.training)[m.key]; return <Histogram key={m.key} title={m.title} values={values} current={typeof current === "number" ? current : null} currentLabel="Activo" format={m.format} color={m.source === "checks" ? SERIES_PROD : SERIES_TRAIN} unit={m.source === "checks" ? "evaluaciones" : "modelos"} />; })}</div>
    </section>
    <section className="grid-main"><article className="panel decision-panel"><div className="panel-head"><div><p className="eyebrow">DECISIÓN EXPLICADA</p><h2>Estado del modelo / Recomendación</h2></div><Badge tone={decisionTone}>{Array.isArray(decision) ? decision[0] : decision}</Badge></div><div className={`decision ${decisionTone}`}><div className="decision-icon">{decisionTone === "green" ? "✓" : "!"}</div><div><strong>{Array.isArray(decision) ? decision[0] : "El modelo está dentro de los parámetros"}</strong><p>{d.reason}</p></div></div><div className="rule-list"><div><span>Variables con PSI ≥ {d.thresholds.psi.toFixed(2)}</span><b>{d.drifted.length} / {d.thresholds.required} requeridas</b></div><div><span>Ratio WAPE actual / baseline</span><b>{fmt(data.performance.ratio)} / {d.thresholds.ratio.toFixed(2)}</b></div><div><span>Última ejecución</span><b>{date(data.executions.latest?.date)}</b></div></div></article><article className="panel performance"><div className="panel-head"><div><p className="eyebrow">RENDIMIENTO</p><h2>Tendencia de WAPE</h2></div><Badge tone="muted">Últimas evaluaciones</Badge></div><LineChart points={data.performance.history} threshold={d.thresholds.ratio} /><div className="legend"><span><i className="legend-line" /> Ratio WAPE</span><span><i className="legend-dash" /> Umbral</span></div></article></section>
    <section className="grid-main"><article className="panel"><div className="panel-head"><div><p className="eyebrow">DATA DRIFT</p><h2>Señales por variable</h2></div><span className="panel-note">Umbral PSI {d.thresholds.psi.toFixed(2)}</span></div><div className="feature-list">{featureNames.map((name) => { const value = Number(d.psi[name] ?? 0); const hit = value >= d.thresholds.psi; return <div className="feature" key={name}><div className="feature-name"><span>{name}</span><Badge tone={hit ? "amber" : "green"}>{hit ? "DRIFT" : "OK"}</Badge></div><div className="bar-wrap"><div className={`bar ${hit ? "hit" : ""}`} style={{ width: `${Math.min(100, (value / Math.max(d.thresholds.psi * 2, 1)) * 100)}%` }} /><div className="bar-threshold" style={{ left: `${Math.min(100, (d.thresholds.psi / Math.max(d.thresholds.psi * 2, 1)) * 100)}%` }} /></div><b>{fmt(value, 3)}</b></div>})}</div></article><article className="panel alerts"><div className="panel-head"><div><p className="eyebrow">SISTEMA</p><h2>Alertas activas</h2></div><span className="alert-count">{(d.alert ? 1 : 0) + (data.executions.failedCount ? 1 : 0)}</span></div><div className="alert-items">{d.maxPsi >= d.thresholds.psi && <div className="alert-item amber"><span>△</span><div><b>PSI sobre umbral</b><small>Máximo {fmt(d.maxPsi, 3)} · umbral {d.thresholds.psi.toFixed(2)}</small></div></div>}{data.performance.ratio >= d.thresholds.ratio && <div className="alert-item red"><span>↗</span><div><b>Rendimiento degradado</b><small>Ratio {fmt(data.performance.ratio)} supera {d.thresholds.ratio.toFixed(2)}</small></div></div>}{data.executions.failedCount > 0 && <div className="alert-item red"><span>×</span><div><b>Ejecución de drift fallida</b><small>{data.executions.failedCount} ejecución(es) con error</small></div></div>}{!d.alert && !data.executions.failedCount && <div className="empty">✓ No hay alertas activas en este momento.</div>}</div><div className="system-foot"><span>Último éxito</span><b>{date(data.executions.lastSuccess)}</b></div></article></section>
    <section className="panel history"><div className="panel-head"><div><p className="eyebrow">AUDITORÍA</p><h2>Historial de drift</h2></div><div className="filters"><button className={filter === "all" ? "selected" : ""} onClick={() => setFilter("all")}>Todas</button><button className={filter === "success" ? "selected" : ""} onClick={() => setFilter("success")}>Exitosas</button><button className={filter === "error" ? "selected" : ""} onClick={() => setFilter("error")}>Fallidas</button><button className={filter === "alert" ? "selected" : ""} onClick={() => setFilter("alert")}>Con alerta</button></div></div><div className="table-scroll"><table><thead><tr><th>Fecha / hora</th><th>Versión</th><th>PSI máx.</th><th>Variables</th><th>WAPE / base</th><th>Ratio</th><th>Resultado</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td>{date(row.date)}</td><td><code>{row.version}</code></td><td>{fmt(row.psi, 3)}</td><td>{row.drifted} / {featureNames.length}</td><td>{pct(row.wape)} <span className="muted">/ {pct(row.baseline)}</span></td><td>{fmt(row.ratio)}</td><td><Badge tone={row.status === "error" ? "red" : row.alert ? "amber" : "green"}>{row.status === "error" ? "ERROR" : row.alert ? "ALERTA" : "OK"}</Badge></td></tr>)}</tbody></table></div></section>
    <section className="panel model-history"><div className="panel-head"><div><p className="eyebrow">REGISTRO DE MODELOS</p><h2>Versiones disponibles</h2></div><span className="panel-note">{data.models.length} versiones registradas</span></div><div className="model-cards">{data.models.map((model: any) => <div className={`model-card ${model.id === data.model?.id ? "active" : ""}`} key={model.id}><div><code>{model.version}</code>{model.id === data.model?.id && <Badge tone="blue">ACTIVO</Badge>}</div><strong>{model.algorithm ?? "Modelo"}</strong><small>{date(model.trainedAt)}</small><span>{model.mlflowModelVersion ? `MLflow v${model.mlflowModelVersion}` : model.mlflowRunId ? `Run ${model.mlflowRunId.slice(0, 10)}…` : "Sin referencia MLflow"}</span></div>)}</div></section>
    <footer>Solo lectura · Las consultas al dashboard no ejecutan drift ni modifican datos de Supabase.</footer>
  </main>;
}
